baseurl = "http://timtrice.net"
relativeurls = true
languageCode = "en-us"
title = "Tim Trice"
theme = "ghostwriter"
googleAnalytics = "UA-1507390-26"
disqusShortname = "timtrice"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
publishDir = "docs"

[Author]
    name = "Tim Trice"
    profile = "https://github.com/timtrice"

[permalinks]
    post = "/:year-:month-:day-:slug/"

[Params]
    intro = true
    headline = "Tim Trice"
    description = "Data Exploration, Management and Analysis"
    github = "https://github.com/timtrice"
    linkedin = "https://www.linkedin.com/in/timtrice/"
    twitter = "https://twitter.com/timtrice"
    stackoverflow = "http://stackoverflow.com/users/2576935/timtrice"
    email = "tim.trice@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
